var INPUT = "fBDGBcBrGDvjPtPtPV\nQhzJLlLJZgLZzNTgZClQHvRvHFvrjrvnNjHnFjPF\nChldsCZhsQzsCGrrSfMfGpfrdM\nMJbgcgJlvMSbfjMSbllmCrntwmFrrFwgtCtFFG\nvPhddVZZhmnmdnHmHn\nvNBZppZQhjSzfScjDN\njwhqbZRvbzvbqqpqzqHHCCCzsLmmQVtmJVJtLWLPrVLLVrmp\ndGMfMGMdBBMSTfdMGTNlcZGGPSmQJVVWsJQPLmPLVPtmWPLW\nllMBBcfBnBcZMGgqvCDbjbwgCHjvzH\nRSDprRrwgVVRwrGqrJsNFJslgglmmNszzN\nLLnWjcHWnCTmpClhHp\nMpfMZWjtLMjpjtBPnLPndMBGRqwbwBwvrGwGrGVbVvwD\nPQNGshQWtwWNcjssJHHJdlBLBlLrRDFFCrdwSlLB\nmbzqZqsgMzfnbmbfgpZvZBLrLlSCrprDlLCrdFBlDL\nMfvZzqMmsVnVzzTTbMzfvnctjhcHPQJJjNTGWjQJJHWP\nMdLWQdMZrPQWsPdMQPLSqGpHGbGqpqqqVzpm\nBhgFhVgnlgBNFtNwzpbTGbTTHpwwbF\ntCfvvCfgvBjnfflftCvjWZVddMQZsMMsRdMZMP\nlTLdHVlqmqWdvjvJttvFlJtC\nngbMTgGhQpgrGtvCzcCJccCrcj\nnpgwnDpSDbgbbnGGDQnMDSMgZZWVqNTNPRRdwLLNLqmPZTLP\nRRSFZvRdrdbSvSVLRZrSGZZrHcHPfPPwJJVJmPHmJfHVThPm\nWnLjBQBCQWqCQwpPmHTcfQpm\ngBDttlnqLqlvzzlGRRlr\nwGpdGdddMPDWgFJGBzmMlntTbZMtZbnT\nqNSqQrrqSjQVrsvTtzNnnZTnfNztZw\nrcVrjjsswVvRRHsFJLCDCpCddGCCcG\njLMhCPWLCSWSrRLPWmPPLSCLtcTvHHDhZcfHHltlfZtlfgfH\nrBBNrbVdtZlvVcZc\nFppGdpFsnsqGJnsFzGdJszbdwSLRSRPrSRjqrMqCwQMWQqRS\njTjZwnpjMDfZnmZfsRhGGztqCzwsdGws\nJHrWcNrNNrJHLHlzsCtzGRRRHv\nrNLrVBJFLmfCnbTpVQ\nLGWJvDFssFmMBhThMvnB\nCprbCNZpwfpwfrbZJMQMTQcVVgBZcVQBZc\nptNwfwzHzqzlttbrlpCCqzwtFLGSWFsPDLWFHSDjJWSDLFDs\nMZJjSsCsMsZSSdZJhdjZtCbPHljqlLPlPRRDLqHHqLbB\nmmwmVpGrnngmggGwnccPbDBPLLLllLBcFRFb\nGQzVTQTTVzVrQrmvpTnmrQmMvZRhZZCZSZfCsfttSJddNC\ngHZZQRdVgRQWWRPHWPnttDTmqQqDQnStzNqD\nbscfjslJJspBLsslNStSmTmLmmDTzNnS\nJJCrbbhBsplrrChpBbfjlpbbFWWVggPPhZVRRFPdVMddPnMg\nFtLfHNhFJCClJlst\njnDQqnDSDSRqwBwnjdFlZbsrTZdsJsGCbw\nzDFSmjSDVqnRMHmphPhfWPgW\nrSpRtSPWpStVqrwSSdrrhZvnBBnDBvsqjlBqvvnnzl\nLFNLLFfFFhMFbcbmbHbHgTNcvZvBZMsvBnJBzsZvjJvZlvnZ\ngmFLhTTbFmmQrrSWWpwWVtwQ\nDzmDJGSccGJPcdcJPJqwplhjBHmHVwwtBthV\ngrMMvRsNRnWCFrgZRrZFhpVVlHVnhpVjVtljhhhf\nFFZFZTsvCMSQTdGcTHzT\nTLsGTnZncjVmVLgm\nDvRwMcHMvMbwBVlCBlzlMjCC\nFdRtRHDwQvPnTfPqcFPP\nrZNdpBSldLLCJZbbCT\nWQcQwqsmQmmqJgTRLRCqLq\nznQcwsmPcmnCzQmfGGnzHSDFlNptNthPSdllhFPplS\nvWCWvVhhjPNjNNvWVNbnbHnrbGrmlPqnqqbw\nJdZSLMgsdgQMcQssQnnDqmDqlDqnDlwrHc\ntdgQSSdpQtSMSNWpWRfRCwjpjV\nqhdJFpChSJhDFDrqbpJbddSHPPRnGGBfBrHfZRnjRnlBZH\nzsMVzmwmtLMtmQTzvwlRcZnZZljvvfGcBjcZ\nttQzMtVgMWVMQsmtJgqJgCJbqhgbBSBN\nBWvdCmZBrNRrGSSfTzQJJRTz\ngMblllMgLVswbgwMsLjgLLnlVtfHfttSQttTJTSQGfGPTPTB\nLMgnMgscgqbFBqvBNFBmNm\nVlcczDZjjVbznwLnwpTH\nNfJPJNfJdJMSHSHnjBRSnbbL\nNddqPttjsdZDqhcqlFcD\nNVrNBBFFFrvJJrVTFTNvWBCbCCgWGqDqhqghCLqbqtCC\nmfZVPZPcqtLbcqgc\nfwZlwzfRfQQPMZBBwwBjFSjTVrBT\nGWWNMfWWwGWMtjJnVnJzlzVsvLnsVn\nZpRqHTBddsvtPLqVPP\nbpSDgStgTbdFTpDdRmfwfmfGFcMQGWMcjQ\ngCgGBgfCbRLbBLGnGBBfRGwprctZFMvtFtvSNNTZZtMvLc\nDhJhDzzQlDdshVJlDdhqzqzQZFpppFMNtMZMtFFVvtpSMpFV\nqQdsDHWWslnNgHmBbHBf\nMRvnJFZVnvzJrWWSqMSPTSNqNj\nGlcbDpCHCCczdsDppcccBGccqjwTTwQPPSjNjWSWSwwsPsws\nGbdlBbgdVtngtzVg\nGqTSRpgJgDNSNJqJlSTJlJCBmmcnjCjLFcMFmnGsmBsM\nHPhfPrWdfrQPPPhQWHbLFFWFCmFjMBFFsLBFwj\nfdzVbvfshrbzvfbfdVPvQtqqJgqgDpNTgqZZtglZtZDD\nwsPhrDMfrwdvHdTFrrtH\nlnQbNBbqVBqHGJSddvTlJJJJ\ncjnHznzbQmgzqQjBWwZwRjDRfWWhWsWD\nSsScnttbbSzRRMMMLpsBLP\ndDJGgjGJVMSBBBMj\nJGDNCfgfSChDJrgqdgqJqGbNbbcbNtzWFctbzzlWtFFn\ndtsBsCMtwSVBlLZZZnMgcMZZ\nbrppQHGznLZgJzJJ\nfprvRpNHpNnvbGDBCBPwBWFWBFBvtB\nqjgjSgHNlSGHnjfSVDvDPRDDtcdDcGtD\nFMTnnLQZtRZDbcZv\nzhBLzrCwnCsTCMCQTFLwwCzpHgNlNmHqhlqSpWllmlllhh\nbJqqFdfbGdfPNsJsdSRCFLRHLDDBHDnShL\nlQWlWQpwQjlpwrjrwTSCTLMCCNTHRDDDDRRB\nwtWgQmQQWtwWwrljNPfGPzJmbbfzmzZf\nMjppbDGmNNblCpzsNZzhNPgHtzzs\nqvdrqrQVVWLfqWfRRPRwZPPwggpf\ncqdcdpqSrrSvrvWvvvrSbcGTTTbGlFFCCcnnGbTb\nHLNfNGttHVFBHWSr\nRZCLsbCbLbLhwzDgbZCbRZhhnpSnnWpWplFFnDnqlBFVpSVB\nMzbhhzwcLGGfGMvMTv\nPdBlpdVJlmftGbTzwbtRTGGL\nNQNMgWNNQNScDhsSHSWhsNgbRCLwGnnwqLwLHbbCGGTjTR\nMvhRMMRvQshgSNDWFrfBfJFZrFPJJJPBBp\nqdtnQqWtnjfGGzsnGQmWWfqQNbRTgggRFNbCFNSSFlSJsrTr\nPZBBbPMvVcMpSRSlSCpCSgCT\nMvHZhwMVLDHDcZMvLQfwGWqwWjqjGbmnQq\nNFPmjNhGthGNpddddFpzBbqPczSqPDzzDgbgLZ\nVJWvwQrlLHWrvlQZDgZSSDSDBqbb\nWfHwMWfvRvMWrWJsrfMRWGFmGGLttMNpjCpTdmFFht\nDppfNpLwhTBRDbblgWNgCdgCvs\nnLcLqFJrHJmLcFmqMFCdzdHdsgvdzvbvWPWs\nnVFqrrQcSVmFjrmJnrFrSjTtRGRLBwfRTfZwhBQhRGGw\nsHrZdHGpHhsrLpsssGLzhrdtWdJTMWJvffVdmnbfJVnW\ncggRDCCjlPQCgDRnfbTtfMJfWVTm\ncCDwQNlwQPjgCFDljwpSLFzGFzZhzsstSpGz\ndGTGpGdPZZCpnnLRpgzgzn\nlflshFjFcrNdBjMjMnmL\nhDfrldDfbVPbQCtHHZ\ncSRZmtFZScfjZtLbmCNMqhMVQCjwqqCwVB\npddczHpHHzgWdGdsvPrPzcvrJMNwJCQwJhNwBhCJBVMpCVJB\ncgrWcHdnPHHznlmftmtLnRDD\nPZFMMVJVZmVJVHMNJNVfNdNNSnSWsSRhgRRQnWSsRnSWmszc\nllljlTwlprClTbTpwLlgQqhcnwnczhcgSqsQRR\nTpCtGtrTBDZVZHNQZQdB\nSggjglBBlzbDgdpFJddZpF\nCCNLsfNfrcMLsTLPfPmndmTwmZtZJZJdJplp\nsfWCqcvMrlMfMLsLNfhVGvjjjSzSzVQhQvVH\nNTBhNhfBvfflsbSmcl\nnrMZRnHHwBMZRsSsgSsGrbmdms\nnPPFVwVWJqJBVJLT\nvvWqWJWJvzfFZZJvWQzqZvdPPHjSfHjssHsbsfbjSHRR\nDCwtDVjMCrltCnCrDCDmbTssPHLTLldssdSldSRp\nnMcGtDmBmMGrGvvvvFhjFZgWcN\ntGWWWfWpMDjMZbTbnqTC\nJFscJzFPDJDJZnrJ\nsBFPcBsSPBvmSPwFzSSQfpwWfDpgNNfWtfgpftfg\nBvTsJJzQJLMlbhmbFlNmTl\nPjGnpdpGcgDmhvnvmvlbmq\ndRtDGGgcDtjRcwdgQLVLRMJsszJVLRQv\nFGbPPfFSchBGSvGGWsjSTLVQLLVTsQlj\ndDzPnCrRCrrWHHTTHsdVjs\nwrwCgzMrNprCwRJJwnnbFmmpGZtcvcbFfPFmFG\nfbrJjmmmZgmZLJZsBBWlCBGnCWdnfF\nRVMDDNDHPNvvRvDtHMcctMqFslqWPnClddlClFlnBqCG\nMDDvHzHVQMMDtTHJLrnggSZLTJZgTL\ndgBBCBBdvbmrRczFMHMSrqjjSPzn\ntZTwQlLVwnQLQQFJVPzjDSSzJFPD\nfhWhQpTTZQlWfQWpWQWQLhBgchhRCsdbvNnbgRsmRR\nLttflLnGrnMsmmHgWTbdMW\nvBSWzZRDccWBFBmJsmPJmgbsgB\nFppcFWRNRZLLppGrGrqr\nJJClRmLlFGvMTlFLLfPFQQcDpQcjFcjqBc\nzgHSZhggggtwSZhrDgsZgbjVQcVcjPNqcpQQqBjNQzNp\nhZnsShSWGDMMMRnv\nRbDbslClhsfNCbsMjbNrjNMfpTTTTJSzHTpLVzLLVWVzJz\nggFGgmqFZBnnSzTWPpHBLzdT\nvmWZWGwcZZqthjDrbclNCjlD\ndCHwnVBBCBnVHddqnQRdbbbrgTsfWwjcWlsfwDDg\nhhlFpMtGJlZmDjfWfscjWDGD\nhFNFvZmppmSlNJMmNFztmzFhdVPPHQQqqHPvLBQnBQQPQPnC\nWfzsplQpvQgfwzlbllPGtPJTTwtGGZBTTGJB\nVrmMjmFDjNjjDFBhHTcZtBRRGcGV\nmqrFmmLrjmjZnmqLrmQsfvbsfsSSlpWqgglp\nlsQVfDpfflpGGmQRRgdQbdfbWdqnjnHnqZHJTqqrWjqqcWnZ\nPPFhFFtwzqjHgjWTWF\nSwMwMhNMlMsgfQfl\ncSttSDQQCgVvQQSvsstthQcslLLgLgLnpglffjfFlLFblnlH\nrTTwTbdBpTHJfZZJ\nBddPBzwMBzqRqddRGbVShvVhVQvQscvGtV\nsSpsHqHMspqMqWsspwsSWsbBPvjrFbddrGTvZLFjdZTZGLLG\nNccDncRVNDVJLvLPPJTJGvJL\nmRCDNNhgDnghNRQNggNRcNlMtpMPMMtHtShlSSMtlhHW\nQrjSFQWzDdCHtpFlbBbVns\nPhJwNLfNqgfdLlZHpZJJpptBBb\nqmwhfhhfMNWSmSdQCddv\nVfRMdbshRmJBqbmDBH\nCWwWCWTCrzFpzWwCWFzgppqHDtZBfqDmQtBftBDFqBtq\nWlzrWWGWPrpGCGdfSsRGVnGVdNnR\nlhLTfppGRhhbZntsbTqMbq\njrHWBHrMgjHPWMgWBJWBWjstPvwFFbbbvtvFqbPtvqws\nrBJJJVWjBjLphcMhSVRV\nfjrBPBjWVPWPrwtjPpRQZZVdZQddFdHFTZdT\nGqlllsGLgMCqGqgTFbmHdTmRzgTm\nqHchGscqGClHGhNwhjJJNWpwPB\nJzrrJZqLFrnMzVjNNnNnNDwdGHGlHlHbpTZDlmpTHb\ngQfQcRWPWgQSStCtfcsPsPmhsGdDhdGDHTwHpDlHwhTG\nfvWQgCtfWgtttcPQcPBtjVdBMJMLJBFJMJVzNrJr\ncMzNjGGNQFVzNNQVjNdqRLbFDqRpgLRDpDHD\nTwtwWJJBJSvmJCWSvTTmTbBpfpRZSfDqqSqDgHLgqdDDqD\nvtvmPrtWQMrbhMrG\nNqCPqJNJQQQQGCtGPmMTrTpHlNdmpTrwdN\nbzhZRDbnZHrmmcwRfM\nvWhsnVWWswhSFvDSDsnhbDsLPqqPFjQjgFgtjqqCLJPgQQ\nnqpfqfcnclcNcjjQ\nBLQJQmLPPvdtTFNjlFNwPs\nDgDgLLCQBBmpVSMrgfqnpp\nnjCnCwwcVCBWjrrhWrHdzJqmhl\nQNGptTTQGLTdhqmdJBHT\nGtLvDDvLMvppGGVZMssfCBMfcfMf\nnpPQGpDnsbJhvldphHFfpl\nmgqZcqzczzzcqmRzrbrzBvfBLvlhhftFWlhlFtLBvv\ncgjmTgbbMgmzqRRwGDDVQVGVSPwTJV\nVhPNvgVhbjPsNvsChTZlHtlwZccZMhwlcm\nfpznDWDzDfRqffpnrmcRmwlTMZrHTBHB\nfWdQLFSnDzpndqzzqgsVvPsJLMsPCgvjPP\nRFRDQVvqVMZGBVzqgqPNJNmNhqqPjnPS\nrcLLCWrtwlWrWlTbTtlLWrWtjPPgdwgjmNmShpJnjSpSjgSg\nLbLTnbbTHsWlfbtZRZGQHHZZDQMVFz\ndwcLLSLVdwLdvdfZNJgQZWfffVJQ\nCTMlCRCCCTCtBmCFMQJNNNbNfWvQjvZggT\nmRnnnpFlvhnlMmBmFMCMCcdHrwzqszprdcwzLDwrSz\nJSHLHRMlzJHcGMpwCffZctZmgfqqZm\nvnTWvQrnrQjNnBWvnvDnVgqtVWwVgfFmqWfqZFWZ\nrdQDBdBrQQhmBNjDTmrTnzPzPPLHSSHzHHRHRLdGLl\nGvMRRwGwRFmZRnmbMhZMGcpgZBpdgBJcTsjsBstdds\nSNlPzzlPDDQSDDDqfllqDLBpTgWBgWdTpcWjJQsWjjTp\nrScrCqPCSLDNrqlFmRVRRrbhmRmFRw\ndbtgMNlNSMQPSLNdvVQgSfcHHfJfHJtfmmHTqZffJH\nwssswnzwChsrGCCwGCjzCsHFHbzZffbFBcffbHHTBJTZ\nrsDRGDwjhWbrbRhGCGLdLNlNQVVDPSlMVMvv\nBgPccPPRlZZmTMTZzZTC\njjNjntVtQnWHrJjFPnnqDqJTJTzqJmDDCqChzS\nFnQHQjHVNnWVvQpgLPGRdcLpbfLLBl\nJLMhFJfHHLJChRvfjLJJnFRpPrpPSrNnrTrTTPntTptrpw\nQgcBCqcGBBGzGrNQNSwSrPPTsr\nzzWdmzcWcdHCJCRRCF\nGSRcjdjGcBnFWbnVLFQR\npCNqTqhDsMsMmNtNCZmMMtdCbVFzbFwnFFnWWFnzVLTQWQLF\nqNJpMdCsDNsNNvGPlSPPJjfBBB\nlsHjgmFsnFTwHgSPDRSrDqnqrrnr\nNmZWcZmzNMZWJbbWvJMJJMzBBBrRrdRfDfppBNqSrrrPBP\nJZQZzQtWJhmltVwVCjwGjs\nDslBHDpdDlslgffFWnGqHfzH\nJNMMCCCCSMvzzGfMzP\nhNtCJTwRwZQbwrplpDjlpz\nvwvJwLBzwhhwvzwrgwshLwVWWgFfmlSFVRDfWFSVFVfF\nmNqbdPnNdpdjnMqSFFMDfSFVMDFRSV\nddpTPTqmbNjjNqndZzvLzJZzHCrrCCzsJH\nSLjjlGMVpLpNSTDspsrHpFFwRrZgRfwpfgFZ\nnQtWPzbPNQtbdzPtbBCQJNPcwFvZJZFFJrwRwrHcfcfrgF\nNQCnqPBWddbPnbCdWdWQnmdVhsMMDsslmSSmMLlVTTDVMm\nFZmcqBChfFmfsDjjnNMNjSDgNs\nRZwzdvdZRvTRRlvWSgDjStnpntDwNMtD\nvHTGRvvvZHlQPRQTbPTVfLJPqcLJBhfmFVJPCF\ndStFcccjFjqGFrFHmSHFBjBvzhpprWZpppbppDvzhsvDhT\nVMVLNfCCCRTTDtDDDTRz\nQLJwMMLnLNVLdtGGgmdScBnB\nnTCWnTnrllglrNgNTZFgSZbddHtdHLLwtMLQtfbM\nBJGqppPCJVmqqhBJCdwwpLSLHddfHSLHtw\nqmzBhczVGsqVBqnFcCjRWNrNlrgD\nphrHLNtnMpslNFfwVGwFZSBfFTTz\ncmJJDmmbCnCCfBSJGVBwfBfz\nDdqdDbcqCPcCQRWmQPqNHhnRMntNNMNhlsLsML\ngHHWJWMWsHWgWSnPwVnVNGGDbnwwTl\nQjThjhFqqhmQTCVPfDVqPbDVVl\nmpFLLrZjjBcmLFmmFtLBJMddMgSdHTscvcJzRHRs\ngRdwcCddwghzddzzzsGfZsGnqlqVVhjGDj\nDMBNpMDHrNrNLFMmpQJHZGnPjFPFlZjlfGVljGVf\nSpbQNmHMzgcRwSSD\ndrqcMpNbpFpmjzfz\nHLGZGsnGLwllzHGGgGnGsBFfmJtmtjfJDSBSJJJB\nZZwQwHTgZnwLGTTnQTHVlgbWCQNhzNcMqbrzcNNQdNcr\nTDScznfzNlpbbrtsvjdcbh\nBBHqFGWGFmVWqVBBWMtvCLvsLdvrvjLjdLbsvm\ntPZHGFJPJqVwMWHJVRRSZNfQnzfpnTpNfl\nFWNZgWCngsNwJwlQlrRTRhSjSS\nGGLcVVcVmppMmpTjTRHlbRbSrVBh\nrvmdzPcdzmzMrCNNPJFntFsCtD\nMtfLBzSLmMtfBMQzMmzmSlfdTDvGCZGCndZnZgWDwGCZ\nHhqrrpppcqhdbjPvbgGvTCnWDbTWZT\ncNjsdqPqchJBlmzlVQLtBJ\nDwwVFZlDBsZFDvLPdpjLjSVHjpLc\nnMnztWhhfPSffcddGpgp\ntQnrQzhzNtzbNrBwPJwTslTvNFFP\nLWMvHJJrJwtzvgwMwVdGfcpNfdDVDWfdBB\njZPFmjnbmhPfTVfVHdhTTV\nqqQCmCmbqCQqjQsQvrQSHSJrzz\nwNzmDRwmgcGphZcPvLLZHjjFLF\nJlbsClVVqDqFZjJD\nWSlnCbttftsCsWftbCCrTffbpdzMwgMgSpRmdwdRzggmDGGg\ngCCRBClgfCgFFTltTGgBqTsQhzLzQQNPnvrNzHrrfPzHLr\nDMjqWSVwDwDwZDHZNvLQnrnrPrNv\nbcmWJqdVcbtgBglbGTCl\nSFDcrFHtlqhqqLdzTTwdJLPNDL\nvBWsWvsmgvvvdPwNnn\nsmfRbpsWMBmsmMsBBBNbtSFttjCHSScbhHtHhHjb\nSQpgGgMNvggQGMvQcgnHWmldnHWTWndnSHHF\nDwbDPzthtttljTzTFBlmzl\nDstCswftDbZbCChPPRrfwsfPQlLccJQLvVGNGNVpMNvZcvgG\nHdqfjjLfHqFSHddVWNBjsWhWRRJtBNBs\ngPMQHpmrcmnbRQNRRJsWttWW\npmbcZwbrPPrnTPMFFdDwqHwvHDvzDq\nFFsVtFGVGvWVhlfVhzlsFvHbPwPmwHLTSbLjcLtbSbLm\nrZrpJwCqnnJHmqcbcTLTbS\nRCZZQMQpzvRhswVg";
//part 2 vars
var rucksacks = INPUT.split("\n");
var elfGroups;
for (var rucksack = void 0; rucksack >= rucksacks.length - 1; rucksack += 3) {
    elfGroups.push(rucksacks.slice(rucksack, rucksack + 3));
    console.log("elf groups update:", elfGroups);
}
/*
// part 2
const findBadges = (elfGroups: string[][]): string[] => {
  console.log(elfGroups[0][0]);
  return [elfGroups[0][0]];
};

const badges: string[] = findBadges(elfGroups);
console.log(badges);

// Used in part 1 also
const getCharPriorities = (chars: string[]): number[] => {
  return chars.map((char) => {
    if (char.charCodeAt(0) >= 97) {
      return char.charCodeAt(0) - 96;
    } else {
      return char.charCodeAt(0) - 38;
    }
  });
};

const priorities: number[] = getCharPriorities(badges);
console.log(priorities);

const prioritySum: number = priorities.reduce((a, b) => a + b, 0);
console.log(prioritySum);
*/
// PART 1 CODE - 8085
/*
const comparts: string[][] = INPUT.split("\n").map((elfItems) => [
  elfItems.slice(0, elfItems.length / 2),
  elfItems.slice(elfItems.length / 2, elfItems.length),
]);

console.log(comparts);

const findSharedItem = (list: string[][]): string[] => {
  let sharedItems: string[] = [];
  for (let rucksack in list) {
    for (let char in list[rucksack][0]) {
      if (list[rucksack][1].includes(list[rucksack][0][char])) {
        sharedItems.push(list[rucksack][0][char]);
        break;
      }
    }
  }
  return sharedItems;
};

const shared = findSharedItem(comparts);
const priorities = getCharPriorities(shared);
const prioritySum = priorities.reduce((a, b) => a + b, 0);

console.log(shared, priorities, prioritySum);
*/
